"use client";

import {useState} from "react";
import {Button} from "@heroui/react";
import {TournamentDrawBoard} from "@/components/tournament_draw";
import type {TournamentDraw} from "@/lib/tournament_draw";
import fixtures from "./fixtures.json";

// Snapshots generated by the backend draw engine using fictional entrants.
const scenarios = fixtures as Record<"single" | "double", {label: string; description: string; state: TournamentDraw}[]>;

export default function DrawDemoPage() {
    const [format, setFormat] = useState<"single" | "double">("double");
    const [step, setStep] = useState(1);
    const snapshots = scenarios[format];
    const current = snapshots[step];
    const completed = current.state.matches.filter(match => match.status === "completed").length;

    return <main className="mx-auto flex w-full max-w-7xl flex-col gap-6 p-4 md:p-8">
        <div>
            <h1 className="text-2xl font-bold">模拟赛事对阵</h1>
            <p className="mt-2 text-sm text-default-500">8 名虚拟选手，可切换赛制与比赛阶段，查看比分如何推进后续对阵。演示数据不会写入真实赛事。</p>
        </div>
        <div className="flex flex-col gap-4 rounded-2xl border border-default-200 p-5 dark:border-white/10">
            <div className="flex flex-wrap items-end gap-4">
                <label className="flex flex-col gap-2 text-sm font-medium">赛制
                    <select value={format} onChange={event => {setFormat(event.target.value as typeof format); setStep(1);}} className="h-10 rounded-xl border border-default-200 bg-surface px-3">
                        <option value="single">单败淘汰</option>
                        <option value="double">双败淘汰（总决赛可重置）</option>
                    </select>
                </label>
                <label className="flex flex-col gap-2 text-sm font-medium">比赛阶段
                    <select value={step} onChange={event => setStep(Number(event.target.value))} className="h-10 rounded-xl border border-default-200 bg-surface px-3">
                        {snapshots.map((snapshot, index) => <option key={snapshot.label} value={index}>{snapshot.label}</option>)}
                    </select>
                </label>
                <Button variant="secondary" isDisabled={step === 0} onPress={() => setStep(value => value - 1)}>上一阶段</Button>
                <Button variant="primary" isDisabled={step === snapshots.length - 1} onPress={() => setStep(value => value + 1)}>下一阶段</Button>
                <span className="pb-2 text-sm text-default-500">已结束 {completed} / {current.state.matches.length} 场</span>
            </div>
            <p aria-live="polite" className="text-sm text-default-600">{current.description}</p>
        </div>
        <TournamentDrawBoard key={`${format}:${step}`} state={current.state}/>
    </main>;
}
