name: Deploy to Server

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install and Build
      run: |
        npm install
        npm run build 

    - name: Clean up old build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          echo "Deleting old .next folder..."
          sudo rm -rf /home/ubuntu/meow/.next
          sudo rm -rf /home/ubuntu/meow/node_modules

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "package.json,package-lock.json,.next,next.config.js,public,.env"
        target: "/home/ubuntu/meow"

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          export NVM_DIR="$HOME/.nvm"
          if [ -s "$NVM_DIR/nvm.sh" ]; then
            \. "$NVM_DIR/nvm.sh"
          else
            echo "nvm not found at $NVM_DIR/nvm.sh"
            exit 1
          fi
          nvm install 24
          nvm alias default 24
          nvm use 24
          node -v
          npm -v
          npm install -g pm2
          pm2 -v
          cd /home/ubuntu/meow
          npm ci --omit=dev
          pm2 restart all --update-env
