name: Docker Build and Push

# 触发工作流的事件
on:
  push:
    branches:
      - main  # 或者任何你想要触发构建的分支
  pull_request:
    branches:
      - main  # 当有 PR 请求合并到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境，使用最新的 Ubuntu

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx (推荐使用 Buildx 来加速和支持多平台构建)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub 或 GitHub Container Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 在 GitHub Secrets 中设置你的 Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # 在 GitHub Secrets 中设置你的 Docker Hub 密码

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .

      # 推送 Docker 镜像到 Docker Hub 或 GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mayumi:${{ github.sha }}
